server_rest = "127.0.0.1:8080"
mongo_binding = "mongodb://127.0.0.1:27017"
mongo_db = "test"


title = "server"
keywords = "server, restful, prototype"
description = "This is a restful server prototype."